import { useEffect, useRef, useState } from 'react'
import { api } from '@/api/client'
import { Button } from '@/components/ui'
import { Icon } from '@/lib/icons'
import type { ContentIR } from '@/types/api'

/** Curated dark-mode gradient palettes matching scene_visual.py */
const CARD_GRADIENTS = [
  'from-[#0f0c29] via-[#302b63] to-[#240b36]', // deep purple
  'from-[#000428] via-[#004e92] to-[#00264d]', // midnight blue
  'from-[#1a1a2e] via-[#16213e] to-[#0f3460]', // dark navy + blue
  'from-[#0d1117] via-[#161b22] to-[#21262d]', // GitHub dark
  'from-[#1b2838] via-[#2a475e] to-[#101822]', // Steam blue
  'from-[#0a0a0a] via-[#1a1a1a] to-[#262626]', // charcoal + gold accent
  'from-[#0f2027] via-[#203a43] to-[#2c5364]', // teal gradient
  'from-[#16001e] via-[#2c0032] to-[#1a001a]', // dark magenta
]

/** Mirrors the backend estimate (2.5 words per second, 1.5 s floor). */
function spokenSeconds(text: string | null | undefined): number {
  const words = (text ?? '').split(/\s+/).filter(Boolean).length
  return words ? Math.max(1.5, words / 2.5) : 0
}

function clock(seconds: number): string {
  const s = Math.round(seconds)
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
}

/** Renders a dynamic content-aware visual image thumbnail generated by the backend for each scene */
/** Renders a dynamic content-aware visual image thumbnail generated by the backend for each scene */
function SceneThumbnailImage({
  outputId,
  sceneIndex,
  title,
  gradient,
  vertical,
  domainLabel,
  from,
  to,
  onPlay,
}: {
  outputId?: string
  sceneIndex: number
  title: string
  gradient: string
  vertical?: boolean
  domainLabel: string
  from: number
  to: number
  onPlay: () => void
}) {
  const [imgError, setImgError] = useState(false)
  const thumbUrl = outputId && !imgError ? api.thumbnailUrl(outputId, sceneIndex) : null

  if (thumbUrl) {
    return (
      <div
        onClick={onPlay}
        className={`group/thumb relative cursor-pointer overflow-hidden rounded-xl bg-black shadow-md ring-1 ring-white/20 transition transform hover:scale-[1.02] ${
          vertical ? 'mx-auto aspect-[9/16] w-36' : 'aspect-video w-full'
        }`}
      >
        <img
          src={thumbUrl}
          alt={title}
          onError={() => setImgError(true)}
          className="h-full w-full object-cover transition duration-300 group-hover/thumb:scale-105"
        />

        {/* Subtle hover dark tint */}
        <div className="absolute inset-0 bg-black/20 opacity-0 transition group-hover/thumb:opacity-100" />

        {/* Center YouTube Red Play Button */}
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-red-600/90 text-white shadow-2xl transition transform group-hover/thumb:scale-110 group-hover/thumb:bg-red-500">
            <Icon name="play" className="ml-1 h-6 w-6 fill-current text-white" />
          </div>
        </div>

        {/* YouTube Timestamp Badge (bottom right) */}
        <div className="absolute bottom-2 right-2 rounded bg-black/90 px-2 py-0.5 font-mono text-[10px] font-bold text-white shadow backdrop-blur-sm ring-1 ring-white/20">
          {clock(from)} – {clock(to)}
        </div>
      </div>
    )
  }

  return (
    <div
      onClick={onPlay}
      className={`group/thumb relative cursor-pointer flex flex-col justify-between overflow-hidden rounded-xl bg-gradient-to-br ${gradient} p-3 shadow-md ring-1 ring-white/20 transition transform group-hover/thumb:scale-[1.02] ${
        vertical ? 'mx-auto aspect-[9/16] w-36' : 'aspect-video w-full'
      }`}
    >
      <div className="absolute inset-0 bg-[radial-gradient(#ffffff_1px,transparent_1px)] [background-size:12px_12px] opacity-15" />
      <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/30" />

      {/* Scene Badge & Domain Pill */}
      <div className="relative z-10 flex items-center justify-between">
        <span className="rounded bg-indigo-600/90 px-1.5 py-0.5 text-[9px] font-extrabold uppercase tracking-wider text-white backdrop-blur-sm ring-1 ring-white/20">
          {domainLabel.split(' ')[0]}
        </span>
        <span className="rounded bg-black/80 px-1.5 py-0.5 font-mono text-[10px] font-bold text-white backdrop-blur-sm">
          SCENE {sceneIndex + 1}
        </span>
      </div>

      {/* Center YouTube Red Play Button */}
      <div className="relative z-10 my-auto flex flex-col items-center justify-center py-1">
        <div className="flex h-10 w-10 items-center justify-center rounded-full bg-red-600/95 text-white shadow-xl transition transform group-hover/thumb:scale-110 group-hover/thumb:bg-red-500">
          <Icon name="play" className="ml-0.5 h-5 w-5 fill-current" />
        </div>
        <div className="mt-1.5 max-w-[90%] rounded-md bg-black/75 px-2 py-0.5 backdrop-blur-md ring-1 ring-white/20">
          <p className="line-clamp-1 text-center text-[11px] font-bold leading-tight text-white">
            {title}
          </p>
        </div>
      </div>

      {/* YouTube-Style Timestamp Badge (bottom right) */}
      <div className="relative z-10 flex items-center justify-between pt-1">
        <span className="text-[9px] font-bold text-slate-200 drop-shadow">Click to Play</span>
        <span className="rounded bg-black/90 px-1.5 py-0.5 font-mono text-[10px] font-bold text-white ring-1 ring-white/20">
          {clock(from)} – {clock(to)}
        </span>
      </div>
    </div>
  )
}

/** Renders a hero video thumbnail poster dynamically matching scene 0 content */
function HeroVideoPoster({
  outputId,
  title,
  scenesCount,
  durationText,
  onClick,
}: {
  outputId?: string
  title: string
  scenesCount: number
  durationText: string
  onClick: () => void
}) {
  const [imgError, setImgError] = useState(false)
  const heroUrl = outputId && !imgError ? api.thumbnailUrl(outputId, 0) : null

  return (
    <div
      onClick={onClick}
      className="group relative mt-6 flex aspect-video cursor-pointer flex-col items-center justify-center overflow-hidden rounded-2xl bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 p-8 text-center shadow-xl transition hover:ring-2 hover:ring-red-500"
    >
      {heroUrl ? (
        <img
          src={heroUrl}
          alt={title}
          onError={() => setImgError(true)}
          className="absolute inset-0 h-full w-full object-cover opacity-80 transition duration-300 group-hover:scale-105"
        />
      ) : (
        <div className="absolute inset-0 bg-[radial-gradient(#ffffff_1px,transparent_1px)] [background-size:16px_16px] opacity-10" />
      )}
      <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-slate-950/40 to-slate-950/60" />

      {/* YouTube Red Play Button */}
      <div className="relative z-10 flex h-20 w-20 items-center justify-center rounded-full bg-red-600 text-white shadow-2xl transition transform group-hover:scale-110 group-hover:bg-red-500">
        <Icon name="play" className="ml-1.5 h-10 w-10 fill-current" />
      </div>
      <h3 className="relative z-10 mt-5 text-xl font-extrabold text-white tracking-tight drop-shadow-md">
        {title}
      </h3>
      <p className="relative z-10 mt-1.5 text-sm font-medium text-slate-200 drop-shadow">
        Click to Play MP4 Video in Fullscreen · {scenesCount} Scenes · {durationText}
      </p>

      {/* YouTube style duration badge */}
      <div className="absolute bottom-4 right-4 rounded-md bg-black/90 px-2.5 py-1 font-mono text-xs font-bold text-white backdrop-blur-sm ring-1 ring-white/20">
        {durationText}
      </div>
    </div>
  )
}

/** The video as a storyboard and interactive embedded video player. */
export default function VideoPreview({
  ir,
  screen,
  outputId,
}: {
  ir: ContentIR
  screen?: string
  outputId?: string
}) {
  const inlineVideoRef = useRef<HTMLVideoElement>(null)
  const modalVideoRef = useRef<HTMLVideoElement>(null)

  const [videoUrl, setVideoUrl] = useState<string | null>(null)
  const [rendering, setRendering] = useState(false)
  const [stage, setStage] = useState<string>('')
  const [error, setError] = useState<string | null>(null)

  // Full-screen player modal state
  const [fullscreenModal, setFullscreenModal] = useState(false)
  const [activeSceneTitle, setActiveSceneTitle] = useState<string>('')
  const [seekTimestamp, setSeekTimestamp] = useState<number>(0)

  const scenes = ir.nodes.filter((n) => n.kind === 'scene')
  const intro = ir.nodes.find((n) => n.kind === 'paragraph')
  const vertical = screen === 'vertical'
  let start = 0
  const timed = scenes.map((s) => {
    const from = start
    start += spokenSeconds(s.text) + 0.5
    return { scene: s, from, to: from + spokenSeconds(s.text) }
  })

  // Auto-check if pre-rendered MP4 video is already available, or auto-render if not yet rendered
  useEffect(() => {
    if (!outputId) return
    let cancelled = false
    api
      .getVideoStatus(outputId)
      .then((status) => {
        if (cancelled) return
        if (status.ready) {
          setVideoUrl(api.videoStreamUrl(outputId))
          setRendering(false)
        } else {
          // If not yet rendered, auto-kickoff render
          renderVideo()
        }
      })
      .catch(() => {
        if (!cancelled) {
          renderVideo()
        }
      })
    return () => {
      cancelled = true
    }
  }, [outputId])

  // Handle ESC key to close full screen modal
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') setFullscreenModal(false)
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [])

  // Sync seek timestamp when modal opens
  useEffect(() => {
    if (fullscreenModal && modalVideoRef.current) {
      modalVideoRef.current.currentTime = seekTimestamp
      modalVideoRef.current.play().catch(() => {})
    }
  }, [fullscreenModal, seekTimestamp])

  async function renderVideo() {
    if (!outputId || rendering) return
    setRendering(true)
    setError(null)
    setStage('Starting video render pipeline...')
    try {
      // 1. Kick off background render job
      const job = await api.renderVideo(outputId)
      // 2. Stream SSE progress frames
      const finalJob = await api.streamJob(job.id, (j) => {
        if (j.stage) setStage(j.stage)
      })

      if (finalJob.status === 'failed') {
        throw new Error(finalJob.error || 'Video rendering failed')
      }

      // 3. Set native stream video URL directly (0-delay start, supports seeking and ranges)
      setVideoUrl(api.videoStreamUrl(outputId))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate video')
    } finally {
      setRendering(false)
    }
  }

  function playScene(sceneTitle: string, timestamp: number) {
    if (inlineVideoRef.current && videoUrl) {
      inlineVideoRef.current.currentTime = timestamp
      inlineVideoRef.current.play().catch(() => {})
      inlineVideoRef.current.scrollIntoView({ behavior: 'smooth', block: 'center' })
    } else {
      playInFullscreen(sceneTitle, timestamp)
    }
  }

  function playInFullscreen(sceneTitle: string, timestamp: number) {
    setActiveSceneTitle(sceneTitle)
    setSeekTimestamp(timestamp)
    setFullscreenModal(true)

    // Trigger render if video is not yet rendered
    if (!videoUrl && !rendering) {
      renderVideo()
    }
  }

  function triggerBrowserFullscreen() {
    const el = modalVideoRef.current || inlineVideoRef.current
    if (el) {
      if (el.requestFullscreen) {
        el.requestFullscreen()
      } else if ((el as any).webkitRequestFullscreen) {
        ;(el as any).webkitRequestFullscreen()
      }
    }
  }

  return (
    <div className="mx-auto w-full max-w-4xl space-y-6">
      {/* Hero Video Header & Player Card */}
      <div className="overflow-hidden rounded-2xl border border-ink-200 bg-white p-6 shadow-sm">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="min-w-0 flex-1">
            <h1 className="text-2xl font-bold tracking-tight text-ink-900">{ir.title}</h1>
            {intro?.text && <p className="mt-2 text-[15px] leading-relaxed text-ink-600">{intro.text}</p>}
            <p className="mt-3 flex items-center gap-3 text-sm text-ink-400">
              <span className="inline-flex items-center gap-1 font-medium text-ink-700">
                <Icon name="video" className="h-4 w-4 text-brand-600" />
                {scenes.length} scenes
              </span>
              <span>·</span>
              <span>about {clock(start)}</span>
              <span>·</span>
              <span className="rounded-md bg-ink-100 px-2 py-0.5 text-xs font-semibold text-ink-700">
                {vertical ? 'Vertical 9:16' : 'Wide 16:9'}
              </span>
            </p>
          </div>

          {outputId && (
            <div className="shrink-0 flex items-center gap-2">
              {videoUrl ? (
                <Button onClick={() => playInFullscreen(ir.title, 0)} variant="primary">
                  <Icon name="play" className="h-4 w-4" />
                  Play Fullscreen
                </Button>
              ) : (
                <Button onClick={renderVideo} disabled={rendering} variant="primary">
                  <Icon name="play" className="h-4 w-4" />
                  {rendering ? 'Rendering video…' : 'Generate & Play MP4'}
                </Button>
              )}
            </div>
          )}
        </div>

        {error && (
          <div className="mt-4 flex flex-col gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 shadow-sm">
            <div className="flex items-center gap-2 font-semibold text-red-800">
              <Icon name="alert" className="h-5 w-5 shrink-0 text-red-600" />
              <span>Video Playback / Fetch Error</span>
            </div>
            <p className="text-red-700 leading-relaxed">{error}</p>
            <div className="pt-1">
              <Button onClick={renderVideo} disabled={rendering} variant="secondary" size="sm">
                <Icon name="play" className="h-3.5 w-3.5" />
                {rendering ? 'Rendering video…' : 'Re-render & Play MP4'}
              </Button>
            </div>
          </div>
        )}

        {/* Video Player Display Container */}
        {videoUrl ? (
          <div className="mt-6 space-y-2">
            <div className="flex items-center justify-between text-xs font-semibold uppercase tracking-wider text-ink-500">
              <span>HD Video Player</span>
              <button
                onClick={() => playInFullscreen(ir.title, 0)}
                className="flex items-center gap-1 text-brand-600 hover:underline"
              >
                <Icon name="play" className="h-3 w-3" />
                Open in Fullscreen
              </button>
            </div>
            <div className="group relative overflow-hidden rounded-2xl bg-black shadow-xl ring-1 ring-ink-950/10">
              <video
                key={videoUrl}
                ref={inlineVideoRef}
                controls
                playsInline
                autoPlay
                src={videoUrl}
                onError={() => {
                  setError('Failed to fetch or decode MP4 video stream. Click "Re-render & Play MP4" to generate a fresh stream.')
                }}
                className={`mx-auto bg-black ${
                  vertical ? 'max-h-[550px] aspect-[9/16]' : 'w-full aspect-video'
                }`}
              />
            </div>
          </div>
        ) : rendering ? (
          <div className="mt-6 flex flex-col items-center justify-center rounded-xl border border-dashed border-brand-300 bg-brand-50/50 p-10 text-center">
            <div className="relative flex h-12 w-12 items-center justify-center">
              <div className="absolute h-full w-full animate-ping rounded-full bg-brand-400 opacity-30" />
              <div className="h-10 w-10 animate-spin rounded-full border-4 border-brand-600 border-t-transparent" />
            </div>
            <p className="mt-4 text-base font-semibold text-ink-900">Generating MP4 Video...</p>
            <p className="mt-1 text-sm font-medium text-brand-600">
              {stage || 'Synthesizing voice-over narration & frame visual graphics...'}
            </p>
            <p className="mt-2 text-xs text-ink-500">
              High-quality H.264 video encoding with MoviePy & gTTS. Takes ~30 seconds.
            </p>
          </div>
        ) : (
          /* YouTube-style Hero Thumbnail Poster prior to render */
          <HeroVideoPoster
            outputId={outputId}
            title={ir.title}
            scenesCount={scenes.length}
            durationText={clock(start)}
            onClick={() => playInFullscreen(ir.title, 0)}
          />
        )}
      </div>

      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold tracking-tight text-ink-900">Scene Breakdown & Video Storyboard</h2>
        <span className="text-xs font-semibold text-brand-600">Click thumbnail or title to play in Fullscreen</span>
      </div>

      {timed.map(({ scene, from, to }, i) => {
        const gradient = CARD_GRADIENTS[i % CARD_GRADIENTS.length]
        const domainLabels = ['CYBER & INFRASTRUCTURE', 'TECHNOLOGY & NETWORK', 'STRATEGY & INNOVATION', 'SECURITY & PROTECTION']
        const domainLabel = domainLabels[i % domainLabels.length]
        return (
          <div
            key={scene.id}
            className="group grid gap-5 rounded-2xl border border-ink-200 bg-white p-5 shadow-sm transition hover:border-brand-400 hover:shadow-lg sm:grid-cols-[14.5rem_minmax(0,1fr)]"
          >
            {/* YouTube-Style Video Thumbnail with Glassmorphic Card & Content-Aware Image */}
            <SceneThumbnailImage
              outputId={outputId}
              sceneIndex={i}
              title={scene.title ?? `Scene ${i + 1}`}
              gradient={gradient}
              vertical={vertical}
              domainLabel={domainLabel}
              from={from}
              to={to}
              onPlay={() => playScene(scene.title ?? `Scene ${i + 1}`, from)}
            />

            {/* Scene Text & Details */}
            <div className="flex flex-col justify-between min-w-0">
              <div>
                <div className="flex flex-wrap items-baseline justify-between gap-2 border-b border-ink-100 pb-2">
                  {/* Clickable Scene Title */}
                  <h3
                    onClick={() => playScene(scene.title ?? `Scene ${i + 1}`, from)}
                    className="cursor-pointer text-lg font-bold text-ink-900 hover:text-brand-600 hover:underline transition"
                  >
                    {scene.title}
                  </h3>
                  <span className="font-mono text-xs font-bold text-ink-600 bg-slate-100 px-2.5 py-1 rounded-md">
                    {clock(from)} – {clock(to)}
                  </span>
                </div>

                {scene.text && (
                  <p className="mt-3 text-[15px] leading-relaxed text-ink-800">
                    <span className="mr-2 inline-block rounded bg-blue-50 px-2 py-0.5 text-[11px] font-bold uppercase tracking-wider text-brand-700">
                      Voice-over
                    </span>
                    {scene.text}
                  </p>
                )}

                {scene.notes && (
                  <p className="mt-2 text-sm leading-relaxed text-ink-600">
                    <span className="mr-2 inline-block rounded bg-slate-100 px-2 py-0.5 text-[11px] font-bold uppercase tracking-wider text-ink-600">
                      Visuals
                    </span>
                    {scene.notes}
                  </p>
                )}
              </div>

              <div className="mt-4 flex items-center gap-3">
                <button
                  onClick={() => playScene(scene.title ?? `Scene ${i + 1}`, from)}
                  className="inline-flex items-center gap-1.5 text-xs font-bold text-brand-600 hover:text-brand-700 hover:underline"
                >
                  <Icon name="play" className="h-4 w-4" />
                  Play scene in Video Player
                </button>
              </div>
            </div>
          </div>
        )
      })}

      {/* Full-Screen Video Lightbox Modal */}
      {fullscreenModal && (
        <div className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black/95 p-4 sm:p-8 backdrop-blur-md animate-fade-in">
          {/* Modal Header Bar */}
          <div className="flex w-full max-w-5xl items-center justify-between pb-4">
            <div>
              <h2 className="text-xl font-extrabold text-white">{ir.title}</h2>
              {activeSceneTitle && (
                <p className="text-sm font-semibold text-brand-400">
                  Playing: {activeSceneTitle} ({clock(seekTimestamp)})
                </p>
              )}
            </div>
            <div className="flex items-center gap-3">
              <Button onClick={triggerBrowserFullscreen} variant="secondary" size="sm">
                Fullscreen
              </Button>
              <button
                onClick={() => setFullscreenModal(false)}
                className="flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-2xl font-bold text-white hover:bg-white/20 transition"
              >
                ✕
              </button>
            </div>
          </div>

          {/* Modal Main Video Container */}
          <div className="relative flex w-full max-w-5xl flex-1 items-center justify-center overflow-hidden rounded-2xl bg-black shadow-2xl ring-1 ring-white/10">
            {videoUrl ? (
              <video
                key={videoUrl}
                ref={modalVideoRef}
                controls
                autoPlay
                src={videoUrl}
                onError={() => {
                  setError('Failed to fetch or decode MP4 video stream. Click "Re-render & Play MP4" to generate a fresh stream.')
                }}
                className={`max-h-[80vh] w-full ${vertical ? 'aspect-[9/16]' : 'aspect-video'}`}
              />
            ) : rendering ? (
              <div className="flex flex-col items-center justify-center p-12 text-center text-white">
                <div className="h-12 w-12 animate-spin rounded-full border-4 border-brand-500 border-t-transparent" />
                <p className="mt-4 text-lg font-bold">Rendering MP4 Video for Fullscreen Playback...</p>
                <p className="mt-1 text-sm text-brand-300">{stage || 'Synthesizing voice-over & video frames...'}</p>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center p-12 text-center text-white">
                <p className="text-lg font-bold">Preparing video stream...</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

