"""consistency issue kinds

Revision ID: 84614ba3fa17
Revises: 4da49fdb1264
Create Date: 2026-09-30 23:31:39.547951
"""

import sqlalchemy as sa

from alembic import op

revision = "84614ba3fa17"
down_revision = "4da49fdb1264"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consistency_issues",
        sa.Column(
            "kind",
            sa.Enum("value_mismatch", "unsourced_number", name="issue_kind", native_enum=False),
            nullable=False,
        ),
    )
    op.alter_column("consistency_issues", "fact_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("consistency_issues", "fact_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("consistency_issues", "kind")
    # ### end Alembic commands ###
